# permissions for end users to view tcproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcproute-viewer-role
rules:
- apiGroups:
  - specs.smi-spec.io
  resources:
  - tcproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - specs.smi-spec.io
  resources:
  - tcproutes/status
  verbs:
  - get
